
apiVersion: v1
kind: Namespace
metadata:
  name: test


---

apiVersion: v1
kind: Service
metadata:
  name: sso
  namespace: test
spec:
  type: ExternalName
  externalName: 127.0.0.1

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sso
  namespace: test
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`sso.app.ieee.elux.ing.unibs.it`) && PathPrefix(`/`)
      services:
        - name: sso
          port: 4443
          scheme: https