ingressClass:
  enabled: true
  isDefaultClass: true

experimental:
  http3: true

ingressRoute:
  dashboard:
    enabled: true

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
    allowEmptyServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    allowEmptyServices: true

additionalArguments:
  - '--api.dashboard=true'
  - '--api.insecure=true'
  - '--accesslog=true'
  - '--accesslog.fields.defaultmode=keep'
  - '--accesslog.fields.headers.defaultmode=drop'
  - '--accesslog.filters.retryattempts'
  - '--serversTransport.insecureSkipVerify=true'

ports:
  web:
    exposedPort: 80
  websecure:
    exposedPort: 443
    http3:
        enabled: true
        advertisedPort: 4443
